#!/bin/sh

image="rootproject/root"

case "$1" in
	sh)
		docker run --rm -it -v "$(realpath files)":/opt/commondir $image bash
		;;
	*)
		docker run \
			-e DISPLAY=$DISPLAY \
			-v /tmp/.X11-unix:/tmp/.X11-unix \
			-v "$(realpath files)":/opt/rootfiles \
			--rm -it $image root --web=off
		;;
esac
