#!/bin/sh

service="ppanalyzer"

case "$1" in

	build)
		docker-compose build
		;;

	sh)
		docker-compose run --rm $service sh
		;;

	nodisplay)
		docker-compose run \
			--rm $service root --web=off
		;;

	*)
		docker-compose run \
			-e DISPLAY=$DISPLAY \
			-v /tmp/.X11-unix:/tmp/.X11-unix \
			--rm $service root --web=off
		;;

esac
