#!/bin/sh
image="rootproject/root"

case "$1" in

	delphes)
		case "$2" in
			build)
				docker build --rm -t delphes delphes
				;;
			sh)
				docker run --rm -it delphes sh
				;;
			*)
				docker run --rm -it delphes
				;;
		esac
		;;

	sh)
		docker run --rm -it -v "$(realpath files)":/opt/commondir $image bash
		;;

	nodisplay)
		docker run \
			-v "$(realpath files)":/opt/rootfiles \
			--rm -it $image root --web=off
		;;

	*)
		docker run \
			-e DISPLAY=$DISPLAY \
			-v /tmp/.X11-unix:/tmp/.X11-unix \
			-v "$(realpath files)":/opt/rootfiles \
			--rm -it $image root --web=off
		;;

esac
