#!/bin/sh

img="mg_wrapper"

if [ -z "$(docker images -q $img 2>/dev/null)" ] || [ "$1" == "build" ]; then
    docker build -t $img .
fi

case "$1" in

   build)
       ;;

	sh)
		docker run --rm -it -v "$(realpath files)":/opt/shared $img bash
		;;

	nodisplay)
		docker run \
			-v "$(realpath files)":/opt/shared \
			--rm -it $img mg5
		;;

	*)
		docker run \
			-e DISPLAY=$DISPLAY \
			-v /tmp/.X11-unix:/tmp/.X11-unix \
			-v "$(realpath files)":/opt/shared \
			--rm -it $img mg5
		;;

esac
